run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    shadow: true
  
  gocyclo:
    min-complexity: 25  # Increased from 15 to be more permissive
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 5  # Increased from 3 to be more permissive
  
  misspell:
    locale: US
  
  lll:
    line-length: 150  # Increased from 120 to be more permissive
  
  goimports:
    local-prefixes: github.com/viniciusamelio/alfred
  
  gosec:
    excludes:
      - G204  # Subprocess launched with potential tainted input
      - G306  # Expect WriteFile permissions to be 0600 or less

linters:
  enable:
    - bodyclose
    - errcheck
    - gochecknoinits
    - gocyclo
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - whitespace
  
  disable:
    - depguard      # Disabled to allow all imports
    - dogsled
    - dupl
    - goconst       # Disabled to allow string repetition
    - gocritic      # Disabled to reduce noise
    - goimports     # Disabled due to formatting issues
    - lll           # Disabled to allow longer lines
    - mnd           # Disabled to allow magic numbers
    - goprintffuncname
    - misspell      # Disabled to allow both cancelled/canceled spellings
    - nakedret
    - prealloc
    - revive        # Disabled to reduce style warnings
    - rowserrcheck
    - stylecheck
    - unconvert
    - unparam

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gosec
    
    - path: cmd/
      linters:
        - errcheck
    
    - path: internal/tui/
      linters:
        - errcheck
        - gosec
    
    - text: "weak cryptographic primitive"
      linters:
        - gosec
        
    - text: "G204"  # Subprocess launched with potential tainted input
      linters:
        - gosec
        
    - text: "G306"  # Expect WriteFile permissions to be 0600 or less
      linters:
        - gosec
  
  max-issues-per-linter: 0
  max-same-issues: 0